### ISSUE TITLE
[feature request] Maybe long arguments should be case-insensitive?

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#8]
I found that long command line arguments are currently case sensitive.

I suggest to update the parsing so that the long command line argument should be converted to first uppercase both the argument passed and the argument to parse, that way we can compare in a case-insensitive way.

Here are two easy ways
Using tr
`echo "$str" | tr '[:lower:]' '[:upper:]'`
Bash only method
`echo ${str^^}`

**Comment by maneyko** [comment]
Using `${str^^}` was introduced in [bash 4](https://tldp.org/LDP/abs/html/abs-guide.html#CASEMODPARAMSUB) which is too far in the future to keep reasonable compatibility. I am using a 2019 MacBook Pro and `/bin/bash` is Bash 3.2.57. I think it's fine that it is case sensitive. If the programmer wrote `arg_optional '[fOoBar] [f] [Some argument]'` then the user should use this convention.

**Comment by maneyko** [comment]
I think having case-sensitive arguments is a fine approach. If a program has arguments defined as:
```bash
arg_optional "[port-number] [p] [The port number.]"
```
and the user does
```bash
./script.sh --Port-Number 2020
```
This should not be supported and the user should refer to the help (if there is any).

However, `argparse.sh` is not totally case insensitive, because you could have two arguments:
```bash
arg_optional "[port-number] [p] [The port number.]"
arg_optional "[Port-Number] [n] [The port number.]"
```
there is no way to distinguish the two because it will be accessible to the user in their script via `ARG_PORT_NUMBER`.

I don't know of any CLIs where this kind of thing is permitted, though, so it seems like the current method is good.
